# Generated by Django 6.0.7 on 2026-08-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medic_search', '0002_cidade_dia_semana_especialidade_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
